{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fiap-microservice.serviceAccountName" . }}
  labels:
{{ include "fiap-microservice.labels" . | indent 4 }}
{{- end -}}
