replicaCount: 1

configmap:
  name: configmap-microservices
  values:
    ENV: docker
    JAVA_OPTS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7000'

strategy:
    maxSurge: 50%
    maxUnavailable: 0
    type: RollingUpdate
    
image:
  repository: wellbastos/fiap-microservices
  tag: 0.0.5
  # digest: "sha256:59b12f40c51c839867d7fded9c095f40756a5b5d2329926d6cdc8996578f9195"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: fiap-microservice

# podSecurityContext:
#   fsGroup: 2000

# securityContext: 
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90
  
service:
  type: ClusterIP
  port: 8080
  healthcheck: /actuator/health
  delaySeconds: 75
  timeout: 1
  periodSeconds: 15

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    # certmanager.k8s.io/issuer: "letsencrypt"
  hosts:
    - host: api.fiap.com.br
      paths: 
        - '/'      
  tls: []
  #  - secretName: tls-api-fiap-com-br
  #    hosts:
  #      - api.fiap.com.br


resources: 
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
