replicaCount: 2

configmap:
  name: consumer
  values:
    APP_NAME: Consumer
    APP_ENV: local
    APP_DEBUG: true
    AMQP_USERNAME: rabbitmq
    AMQP_PASSWORD: rabbitmq
    AMQP_HOST: fiap-rabbit
    AMQP_PORT: 5672
    AMQP_VHOST: '/'
    AMQP_EXCHANGE_NAME: userRegistrations
    AMQP_EXCHANGE_TYPE: fanout

secret:
  name: consumer
  values: 
    APP_KEY: 'and4lvch4HIe73Iw/JEQN6gh3YWCI0nk54rdOnaIKEQ='
    SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'

strategy:
    maxSurge: 50%
    maxUnavailable: 0
    type: RollingUpdate

image:
  repository: wellbastos/consumer-php
  tag: 0.0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "consumer-php"
fullnameOverride: ""

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90

serviceAccount:
  create: true
  name: consumer
 
# podSecurityContext:
#   fsGroup: 2000

# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  # healthcheck: /health
  # delaySeconds: 75
  # timeout: 1
  # periodSeconds: 15

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 500
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
